name: CI

on:
  push:
    branches:
      - master

jobs:
  Build:
    name: instance-build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Greet User
        run: echo "Welcome"

      - name: Generate Version Number
        id: version
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          VERSION="v${TIMESTAMP}_${RANDOM}"
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_ENV  # Set the version as a GitHub environment variable
          
      - name: Build the Docker Image
        env:
          image_name: test-image
          username: dapper01
          APP_VERSION: ${{ env.APP_VERSION }}  # Use the environment variable for version
        run: |
          docker build -t $username/$image_name:${{ env.APP_VERSION }} .
          docker save -o test-image_${{ env.APP_VERSION }}.tar $username/$image_name:${{ env.APP_VERSION }}

      - name: Upload Docker Image as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: test-image_${{ env.APP_VERSION }}.tar  # Match the saved tar file name with the upload path

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: oladapper@gmail.com
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Docker Image Built and Saved"
          to: "oladapolawal12@yahoo.com"
          from: "Mr David Agba DevOps"
          body: |
            Hello
            The latest version of the Docker image (version: ${{ env.APP_VERSION }}) has been built and saved as an artifact.

  

  Deploy:
    name: Deploy Docker Image
    if: github.ref == 'refs/heads/master'
    runs-on: self-hosted
    needs: Build
    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .

      - name: Load Docker Image
        env:
          image_name: test-image
          APP_VERSION: ${{ env.APP_VERSION }} 
        run: |
          docker load -i test-image_${{ env.APP_VERSION }}.tar

      - name: Run Docker Containers
        env:
          image_name: test-image
          APP_VERSION: ${{ env.APP_VERSION }} 
        run: |
          docker run -d -p 8081:80 $image_name:${{ env.APP_VERSION }}

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: oladapper@gmail.com
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Docker Image Deployed from Artifact"
          to: "oladapolawal12@yahoo.com"
          from: "Mr david agba devops"
          body: |
            Hello,
            The latest version of the Docker image (version: ${{ env.APP_VERSION }}) has been deployed from the artifact.
