Deploy:
  name: Deploy Docker Image
  if: github.ref == 'refs/heads/master'
  runs-on: self-hosted
  needs: Build
  steps:
    - name: Download Docker Image Artifact
      uses: actions/download-artifact@v4
      with:
        name: docker-image
        path: .

    - name: Verify Artifact Download
      run: |
        # List the files to verify the artifact is downloaded
        ls -al
        if [ -f "test-image_${{ env.APP_VERSION }}.tar" ]; then
          echo "Artifact found"
        else
          echo "Artifact not found"
        fi

    - name: Load Docker Image
      env:
        image_name: test-image
        APP_VERSION: ${{ env.APP_VERSION }}  # Reference the environment variable correctly
      run: |
        # Check if the artifact exists and load it
        if [ -f "test-image_${{ env.APP_VERSION }}.tar" ]; then
          docker load -i test-image_${{ env.APP_VERSION }}.tar
        else
          echo "File test-image_${{ env.APP_VERSION }}.tar not found, aborting."
          exit 1
        fi

    - name: Run Docker Containers
      env:
        image_name: test-image
        APP_VERSION: ${{ env.APP_VERSION }}
      run: |
        docker run -d -p 8081:80 $image_name:${{ env.APP_VERSION }}

    - name: Send email notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        secure: true
        username: oladapper@gmail.com
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Docker Image Deployed from Artifact"
        to: "oladapolawal12@yahoo.com"
        from: "Mr david agba devOps"
        body: |
          Hello,
          The latest version of the Docker image (version: ${{ env.APP_VERSION }}) has been deployed from the artifact.
