name: CI

on:
  push:
    branches:
      - master

jobs:
  Build:
    name: instance-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Version Number
        id: version
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          VERSION="v${TIMESTAMP}_${RANDOM}"
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV
          echo "::set-output name=version::$VERSION"  

      - name: Build the Docker Image
        env:
          image_name: test-image
          username: dapper01
          APP_VERSION: ${{ steps.version.outputs.version }}  
        run: |
          docker build -t $username/$image_name:${{ env.APP_VERSION }} .
          docker save -o test-image_${{ env.APP_VERSION }}.tar $username/$image_name:${{ env.APP_VERSION }}

      - name: Upload Docker Image as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: test-image_${{ env.APP_VERSION }}.tar

    outputs:
      app_version: ${{ steps.version.outputs.version }}  

  Deploy:
    name: Deploy Docker Image
    runs-on: self-hosted
    needs: Build  # Ensure Deploy runs after Build job
    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .

      - name: Verify Artifact Download
        run: |
          ls -al
          if [ -f "test-image_${{ needs.Build.outputs.app_version }}.tar" ]; then
            echo "Artifact found"
          else
            echo "Artifact not found"
            exit 1
          fi

      - name: Load Docker Image
        env:
          image_name: test-image
          APP_VERSION: ${{ needs.Build.outputs.app_version }} 
        run: |
          if [ -f "test-image_${{ needs.Build.outputs.app_version }}.tar" ]; then
            docker load -i test-image_${{ needs.Build.outputs.app_version }}.tar
          else
            echo "File test-image_${{ needs.Build.outputs.app_version }}.tar not found, aborting."
            exit 1
          fi

      - name: Run Docker Containers
        env:
          image_name: test-image
          APP_VERSION: ${{ needs.Build.outputs.app_version }} 
        run: |
          docker run -d -p 8081:80 $image_name:${{ needs.Build.outputs.app_version }}
