name: todo-app
on:
  push:
    branches:
      - master
jobs:
  Build:
  name: instance build
  if: github.ref == 'refs/heads/master'
  runs-on: ubuntu-latest
  steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Greet User
        run: |
          echo "Welcome"
      # assigning a random number as version
      - name: generate a random version
        run: |
          APP_VERSION=${{RANDOM}}
          echo "APP_VERSION=${APP_VERSION}" >> GITHUB.ENV

      - name: Create app_version.txt
        run: |
          echo "Version: $version" > app_version.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app_version
          path: app_version.txt

      

      - name: Install dependencies
        run: npm install             
      -  name: Run Tests
         run: npm tests
            npm test || { echo 'Tests failed'; exit 1; }


  Deploy:
      - name: instance deploy
        runs-on: self-hosted
        needs: Build
        steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: set up node js
        uses: actions/checkout@v4
        with: 
           node-version: 20

      - name: install dependencies
        run: npm     



     